CREATE TABLE PAPEL (
	PAPEL_ID INTEGER IDENTITY,
	DESCRICAO varchar(100) NOT NULL
);

INSERT INTO PAPEL ("DESCRICAO") VALUES ('cliente');
INSERT INTO PAPEL ("DESCRICAO") VALUES ('fornecedor');

CREATE TABLE USUARIOS (
	USUARIO_ID INTEGER IDENTITY,
	PAPEL INTEGER,
	LOGIN varchar(100) NOT NULL,
	SENHA varchar(100) NOT NULL
);

INSERT INTO USUARIOS ("LOGIN","SENHA","PAPEL") VALUES ('adminC','admin',0);
INSERT INTO USUARIOS ("LOGIN","SENHA","PAPEL") VALUES ('adminF','admin',1);

CREATE TABLE CLIENTE (
	CLIENTE_ID INTEGER IDENTITY,
	CNPJ varchar(100),
	CPF varchar(100),
	USUARIO_ID INTEGER NOT NULL,
);

INSERT INTO CLIENTE ("USUARIO_ID") VALUES (0);

CREATE TABLE FORNECEDOR (
	FORNECEDOR_ID INTEGER IDENTITY,
	USUARIO_ID INTEGER NOT NULL,
);

INSERT INTO FORNECEDOR ("USUARIO_ID") VALUES (1);