CREATE TABLE PAPEL (
	PAPEL_ID SERIAL PRIMARY KEY,
	DESCRICAO varchar(100) NOT NULL
);

INSERT INTO PAPEL (DESCRICAO) VALUES ('cliente');
INSERT INTO PAPEL (DESCRICAO) VALUES ('fornecedor');

CREATE TABLE USUARIO (
	USUARIO_ID SERIAL PRIMARY KEY,
	PAPEL INTEGER,
	LOGIN varchar(100) NOT NULL,
	SENHA varchar(100) NOT NULL,
	CNPJ varchar(100) NOT NULL,
	BAIRRO varchar(100) NOT NULL,
	ENDERECO varchar(200) NOT NULL	
);

ALTER TABLE USUARIO ADD CONSTRAINT FK FOREIGN KEY (papel) REFERENCES PAPEL (PAPEL_ID);

CREATE TABLE CLIENTE(
	CLIENTE_ID SERIAL PRIMARY KEY,
	CATEGORIA varchar(100),
	USUARIO_ID INTEGER
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID);

CREATE TABLE FORNECEDOR(
	FORNECEDOR_ID SERIAL PRIMARY KEY,
	TIPO_NEGOCIO varchar(100),
	USUARIO_ID INTEGER
);

ALTER TABLE FORNECEDOR ADD CONSTRAINT FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID);

CREATE TABLE ORCAMENTO(
	ORCAMENTO_ID SERIAL PRIMARY KEY,
	DESCRICAO varchar(250),
	VALOR decimal,
	PRAZO DATE,
	FORNECEDOR_ID INTEGER,
	LICITACAO_ID INTEGER,
	ITEM_ORCAMENTO_ID INTEGER
);

CREATE TABLE LICITACAO(
	LICITACAO_ID SERIAL PRIMARY KEY,
	DESCRICAO varchar(250),
	DATA_INICIO DATE,
	DATA_FIM DATE,
	CLIENTE_ID INTEGER,
	ITEM_LICITACAO_ID INTEGER
);
	
ALTER TABLE LICITACAO ADD CONSTRAINT FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID);	



ALTER TABLE ORCAMENTO ADD CONSTRAINT FK FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (FORNECEDOR_ID);	
	

ALTER TABLE ORCAMENTO ADD CONSTRAINT FK2 FOREIGN KEY (LICITACAO_ID) REFERENCES LICITACAO (LICITACAO_ID);	
	

CREATE TABLE ITEM_ORCAMENTO(
	ITEM_ORCAMENTO_ID SERIAL PRIMARY KEY,
	PRODUTO_ID INTEGER,
	ORCAMENTO_ID INTEGER,
	QUANTIDADE INTEGER
)

CREATE TABLE ITEM_LICITACAO(
	ITEM_LICITACAO_ID SERIAL PRIMARY KEY,
	PRODUTO_ID INTEGER,
	LICITACAO_ID INTEGER,
	QUANTIDADE INTEGER
)

CREATE TABLE PRODUTO(
	PRODUTO_ID SERIAL PRIMARY KEY,
	NOME varchar(100),
	DESCRICAO varchar(250)
)


ALTER TABLE ORCAMENTO ADD CONSTRAINT FK3 FOREIGN KEY (ITEM_ORCAMENTO_ID) REFERENCES ITEM_ORCAMENTO (ITEM_ORCAMENTO_ID);	



ALTER TABLE LICITACAO ADD CONSTRAINT FK2 FOREIGN KEY (ITEM_LICITACAO_ID) REFERENCES ITEM_LICITACAO (ITEM_LICITACAO_ID);	

ALTER TABLE ITEM_ORCAMENTO ADD CONSTRAINT FK FOREIGN KEY (ORCAMENTO_ID) REFERENCES ORCAMENTO (ORCAMENTO_ID);	

ALTER TABLE ITEM_ORCAMENTO ADD CONSTRAINT FK2 FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID);


ALTER TABLE ITEM_LICITACAO ADD CONSTRAINT FK FOREIGN KEY (LICITACAO_ID) REFERENCES LICITACAO (LICITACAO_ID);	

ALTER TABLE ITEM_LICITACAO ADD CONSTRAINT FK2 FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID);
